### ISSUE TITLE
Invalid Privacy Manifest - Testflight Rejecting iOS Builds

### ISSUE THREAD

**Issue by DavePilks** [newrelic/newrelic-maui-plugin#28]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Trying to submit to Testflight, the build is available for about 5 minutes before it is kicked out due to it being an "Invalid Binary". An email is then sent out saying:

> Hello,
> 
> We noticed one or more issues with a recent submission for TestFlight review for the following app:
> 
> << AppName >>
> << AppVersion >>
> << AppBuildNumber >>
> Please correct the following issues and upload a new binary to App Store Connect.
> 
> ITMS-91056: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/NewRelic.framework/PrivacyInfo.xcprivacy”. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.
> 
> Apple Developer Relations

## Your Environment

Currently using v0.0.9

## Additional context

Seems to be related to [this issue](https://github.com/newrelic/newrelic-react-native-agent/issues/160) logged in the React Native library repo

**Comment by ndesai-newrelic** [comment]
@DavePilks we will look into this.

**Comment by DavePilks** [comment]
Thank you as this is obviously a major blocker for us at the moment

**Comment by ndesai-newrelic** [comment]
@DavePilks i tried to reproduce the issue on our side but I am not getting the error while I submit app for review. 

can you tell me how are you building the app?  are you using windows machine or mac machine ?

**Comment by DavePilks** [comment]
@ndesai-newrelic 

So that is the odd thing. If I verify the build using Transporter, I dont get any errors. When I submit for review I dont get any errors. But after about 5-10 minutes, Apple kicks out the build stating that its an invalid binary and the email I attached above is sent out.

> can you tell me how are you building the app? are you using windows machine or mac machine ?

I am building off a M2 Mac and using the DotNet CLI

`dotnet publish -f net8.0-ios -c Release -p:ArchiveOnBuild=true -p:RuntimeIdentifier=ios-arm64 '-p:CodesignKey="Apple Distribution: <<NAME>>"' -p:CodesignProvision="<<PROFILE NAME>>"`

And this has been working for us until this week where it seems that Apple has started enforcing their Privacy Manifest policy.

**Comment by ndesai-newrelic** [comment]
@DavePilks are you still having this issue?
