### ISSUE TITLE
 CrossNewRelic.Current.LogAttributes generates an Info with <invalid message>

### ISSUE THREAD

**Issue by JimWilcox3** [newrelic/newrelic-maui-plugin#36]
## Description
Whenever I use CrossNewRelic.Current.LogAttributes to log an event, it also logs a corresponding Info event immediately before that says <invalid message> in the message column

## Steps to Reproduce

 var attr = new Dictionary<string, object>
 {
     { "application", ApplicationName },
     { "DeviceId", MPS.GetDeviceID() },
     { "UserId", Settings.UserName ?? "" }
 };
 attr.Add("level", "DEBUG");
 attr.Add("message", message);
 CrossNewRelic.Current.LogAttributes(attr);

## Expected Behavior

I expect a single Debug level log entry in the NewRelic Console.

## Relevant Logs / Console output

This is a .csv export of the pertinent logs.

DeviceId,UserId,application,level,message,messageId,newrelic.logPattern,newrelic.logs.batchIndex,newrelic.source,stack_trace,timestamp
a4af2ad09c88b766,1547,MyApp,INFO,<invalid message>,a7b901aa-143c-4190-9e62-2715ee706093,nr.DID_NOT_MATCH,31,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,DEBUG,Async Saved object of type: MyApp.Droid.SettingsStorage,e5e1e887-c41c-4656-a632-c3c984d931b3,nr.DID_NOT_MATCH,32,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,INFO,<invalid message>,4b7cc8f7-251b-49ab-a0c1-d4e857f77ccd,nr.DID_NOT_MATCH,33,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,DEBUG,Async Saved object of type: MyApp.Droid.SettingsStorage,fd283c95-d28d-47e0-9103-15e6b51a2a01,nr.DID_NOT_MATCH,34,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,INFO,<invalid message>,cd4d2731-ab4b-45bf-b4de-4c3781c19290,nr.DID_NOT_MATCH,35,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,DEBUG,Async Saved object of type: MyApp.Droid.SettingsStorage,7b7a6bb1-25ee-4fc3-bb1e-40456d101846,nr.DID_NOT_MATCH,36,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,INFO,<invalid message>,9e9e730b-95f5-43c9-8ae0-05d60302ed98,nr.DID_NOT_MATCH,37,api.logs,,1.72193E+12
a4af2ad09c88b766,1547,MyApp,DEBUG,Async Saved object of type: MyApp.Droid.SettingsStorage,21b72cd1-f6d4-4c8e-975c-3c16467a12dc,nr.DID_NOT_MATCH,38,api.logs,,1.72193E+12

## Your Environment

HW: Android Tablet: Android version 14

App: .net8.0-android project.  Nuget = NewRelic.MAUI.Plugin  

## Additional context

One other note is that the NewRelic Console doesn't receive the log entries until my app quits and starts back up.  Then it sends all the logs created using any CrossNewRelic.Current.Log*** method.  It sends logs for the NewRelic engine starting up immediately.

**Comment by ndesai-newrelic** [comment]
@JimWilcox3 we will check it from our side.

**Comment by ndesai-newrelic** [comment]
@JimWilcox3 i am able to send this log messages from our side.
<img width="538" alt="Screenshot 2024-07-30 at 8 48 49 AM" src="https://github.com/user-attachments/assets/861f7933-ce24-46a6-bf67-4e5090ee886e">

**Comment by JimWilcox3** [comment]
@ndesai-newrelic 
It didn't include a log entry with a blank message when it sent?

**Comment by ndesai-newrelic** [comment]
nope, i can see the message on log entry.

**Comment by JimWilcox3** [comment]
@ndesai-newrelic 
Did you see the comma delimited section I put under "relevant logs"?

**Comment by ndesai-newrelic** [comment]
@JimWilcox3 is it still the issue?

**Comment by JimWilcox3** [comment]
Hey,

I quit trying to use Log Attributes.  I would up just using the Serilog plugin and I created an Enricher:

```
 public void Enrich(LogEvent logEvent, ILogEventPropertyFactory pf)
 {
     logEvent.AddPropertyIfAbsent(pf.CreateProperty("DeviceId", MPS.GetDeviceID()));
     logEvent.AddPropertyIfAbsent(pf.CreateProperty("UserId", Settings.UserName));
     if (!string.IsNullOrEmpty(Settings.NewRelicGuid))
         logEvent.AddPropertyIfAbsent(pf.CreateProperty("entity.guid", Settings.NewRelicGuid));
 }

```
It's not perfect, but it is working acceptably for what I need.
