### ISSUE TITLE
iOS app not reporting unhandled crashes

### ISSUE THREAD

**Issue by sgreifeneder** [newrelic/newrelic-maui-plugin#42]
## Description

I've set up 2 entities in NewRelic, one for Android and one for iOS. 
It should monitor some basic app usages, but also (un)handled crashes. 

I've followed the readme to setup my MAUI app: 

In `MauiProgram.cs`:
```
			.ConfigureLifecycleEvents(lifecycle =>
			{
#if ANDROID
				lifecycle.AddAndroid(android => android.OnCreate((activity, savedInstanceState) => StartNewRelic()));
#endif
#if IOS
				lifecycle.AddiOS(ios => ios.WillFinishLaunching((_, __) =>
				{
					StartNewRelic();
					return false;
				}));
#endif
			})
```

```
	private static void StartNewRelic()
	{
		CrossNewRelic.Current.HandleUncaughtException();

		if (DeviceInfo.Current.Platform == DevicePlatform.Android)
		{
			CrossNewRelic.Current.Start("xxxxxxxx");
		}
		else if (DeviceInfo.Current.Platform == DevicePlatform.iOS)
		{
			CrossNewRelic.Current.Start("xxxxxxxxx");
		}
	}
```

Now, when I try to manual trigger crashes/exceptions, they will show up in NewRelic dashboard for Android but not for iOS.

## Steps to Reproduce

- Integrate NewRelic as per the readme
- add a basic page with a button
- on button click: `throw new Exception(...);` or `CrossNewRelic.Current.CrashNow();` to simulate a crash

## Expected Behavior

Crash should show up in NewRelic dashboard.

**Comment by akrol95** [comment]
I have the same problem. I am using the latest version of the package (1.1.1).

**Comment by akrol95** [comment]
I fixed the issue. It was on my side.

In my code there was tyr...catch block around:

` UIApplication.Main(args, null, typeof(AppDelegate));
`

and it was blocking NewRelic mechanism from saving the exception.
Now crashes are reported correctly.

**Comment by sgreifeneder** [comment]
It seems that not all crashes are reported, but I can't reproduce that yet. 
However, the biggest issue is something else: just learnt from NewRelic support, that MAUI apps don't support symbolication on iOS ... so that's useless anyway because you can't read crash reports.

**Comment by ndesai-newrelic** [comment]
@sgreifeneder @akrol95 have you trie to upload dsysm using this? https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/configuration/upload-dsyms-bitcode-apps/#manual-dsym

**Comment by ndesai-newrelic** [comment]
@sgreifeneder @akrol95 To capture unhandled exceptions in iOS, you can introduce the following code when initializing the agent. We will start capturing these exceptions from the next release:

```csharp
AppDomain.CurrentDomain.UnhandledException += (s, e) =>
{
    CrossNewRelic.Current.RecordException((Exception)e.ExceptionObject);
};
```

**Comment by sgreifeneder** [comment]
@ndesai-newrelic I'm already manually uploading the dSYM file. The issue is something else.

As per https://forum.newrelic.com/s/hubtopic/aAXPh0000000kyvOAA/autouploading-dsym-for-net-maui-ios-app-built-solely-with-visualstudio2022:
> Please note that although, you are able to upload the dSYMs, they won't symbolicate the stack traces for a platform other than iOS because our hybrid agents (including the MAUI plugin) don't currently support the symbolication of crashes.

**Comment by ndesai-newrelic** [comment]
@sgreifeneder They are discussing .NET symbolication. We provide support for iOS crash symbolication using dsyms. Have you attempted to use the unhandled exception code that I recommended?

**Comment by sgreifeneder** [comment]
Where should I add this? 
After `CrossNewRelic.Current.Start(...)` and only for iOS?

**Comment by ndesai-newrelic** [comment]
@sgreifeneder you can add after you start agent. it is only for iOS.

**Comment by sgreifeneder** [comment]
ok will try

**Comment by sgreifeneder** [comment]
Are you referring to v1.1.4 of the New Relic .NET MAUI mobile plugin, released on Oct 11th?

**Comment by sgreifeneder** [comment]
I am using v1.1.1 in production, and I released an Android and iOS app (built with .NET MAUI) approx. 2 weeks ago. While Android seems to be reporting fine, on iOS I'm missing: monthly active users (it's just 0), devices, OS versions, ... basically everything that's under USERS in the NewRelic menu for my app.
I hope that's fixed with v1.1.4? Because I need to report these numbers on a monthly basis to my customers ...

**Comment by ndesai-newrelic** [comment]
@sgreifeneder can you test it with 1.1.4? it should fixed all the issues.

**Comment by sgreifeneder** [comment]
@ndesai-newrelic I had a quick test with 1.1.4 locally on my iPhone and I could see some data coming in. Will update here again once I release my app.

**Comment by sgreifeneder** [comment]
@ndesai-newrelic while it's working locally, my app crashes immediately when opened from TestFlight (everytime). Maybe an issue with release builds, I'm investigating it currently ... any known issues there?
