### ISSUE TITLE
'iOS" is  a namespace but is used like a type error when adding the NewRelic nuget

### ISSUE THREAD

**Issue by robin-schroeder-merc** [newrelic/newrelic-maui-plugin#45]
After I add the NewRelic.MAUI.Plugin to my .Net MAUI solution, I get compiler errors. I was also able to reproduce this with a brand new .Net MAUI sln. If I remove the NewRelic.MAUI.Plugin nuget package, the following compiler errors disappear. 

[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
1. Create a brand new .Net MAUI Application with .Net 8. 
2. Notice you can compile successfully.
3. Open your AppShell.xaml.cs and add the following after the InitializeComponent();
var safeInsets = On<iOS>().SafeAreaInsets();
4. Notice you can compile successfully.
5. Add Nuget package NewRelic.MAUI.Plugin
4. Notice that you cannot compile anymore. The errors are as follows:
- Error (active)	CS0118	'iOS' is a namespace but is used like a type	MauiApp3 (net8.0-ios)	C:\Code\MauiApp3\MauiApp3\AppShell.xaml.cs	12	
- Error (active)	CS1929	'IPlatformElementConfiguration<iOS, Page>' does not contain a definition for 'SafeAreaInsets' and the best extension method overload 'Page.SafeAreaInsets(IPlatformElementConfiguration<iOS, Page>)' requires a receiver of type 'Microsoft.Maui.Controls.IPlatformElementConfiguration<Microsoft.Maui.Controls.PlatformConfiguration.iOS, Microsoft.Maui.Controls.Page>'	MauiApp3 (net8.0-ios)	C:\Code\MauiApp3\MauiApp3\AppShell.xaml.cs	12	

[NOTE]: # ( Please be as specific as possible. )

## Expected Behavior
I would expect it to compile successfully.

[NOTE]: # ( Tell us what you expected to happen. )

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment
Visual Studio (PC) Version 17.11.0

## Additional context
You can read more about the Safe Insets feature in MAUI here: [https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout?view=net-maui-8.0](https://learn.microsoft.com/en-us/dotnet/maui/ios/platform-specifics/page-safe-area-layout?view=net-maui-8.0)

**Comment by robin-schroeder-merc** [comment]
![image](https://github.com/user-attachments/assets/059a896f-f644-46e3-af20-17da7e2d106b)

**Comment by ndesai-newrelic** [comment]
@robin-schroeder-merc i will look into it.

**Comment by ndesai-newrelic** [comment]
@robin-schroeder-merc we created internal ticket for this, it will fix in next maui agent release.

**Comment by robin-schroeder-merc** [comment]
Thank you! It works!
