### ISSUE TITLE
NullReferenceException on iOS startup for TrackShellNavigatedEvents

### ISSUE THREAD

**Issue by InquisitorJax** [newrelic/newrelic-maui-plugin#52]
I'm getting a null reference exception when calling CrossNewRelic.Current.TrackShellNavigatedEvents() on iOS

Seems the same thing was reported here: 
https://forum.newrelic.com/s/hubtopic/aAXPh0000002GOrOAM/mobile-xamarin-issue-track-events

code is called from:
 AppLifecycle.AddiOS(iOS => iOS.WillFinishLaunching((_,__) => {
    StartNewRelic();
    return false;
}));

## Your Environment

latest Visual Studio 17.11.5
nuget version 1.1.4

**Comment by ndesai-newrelic** [comment]
@InquisitorJax where are you calling this ? it should called after you created AppShell for the App.

**Comment by InquisitorJax** [comment]
I just followed the documentation that shows it being added along with the HandleUncaughtException call in the WillFinishLuanching method.
I guess this is too soon since the app shell hasn't been assigned yet when this iOS event occurs.
I moved it to after AppShell is assigned to MainPage, and that seems to work fine.
