### ISSUE TITLE
Crash when intractionTracingEnabled turned on, iOS Only, release mode only, no linker

### ISSUE THREAD

**Issue by robin-schroeder-merc** [newrelic/newrelic-maui-plugin#54]
## Description
When initializing the agent during startup as follows, our app experiences a crash, only on iOS and only in Release mode. 
nr_plugin.AgentStartConfiguration agentConfig = new nr_plugin.AgentStartConfiguration();

The crash could be reproduce while building release mode locally and building release mode in our automated pipeline. All versions of .Net used are pinned to 8.0.402 and matching workloads are pinned locally and in the pipeline.

The crash report was no help and only contained SIGBRT codes. When I looked in the console during the crash, I noticed only the following error right before the crash.
![image](https://github.com/user-attachments/assets/0af42d96-f8cb-4b17-bf2c-4c215ca552fd)

If I break out all of the default settings, and I turn OFF the interactionTracingEnabled, then the crash doesn't occur anymore. In our previous app release, we did not experience any issues, but recently we changed around some of our navigation, particularly our tab navigation. It is possible that some of that is triggering a problem? But proper navigation is not optional...  You mentioned in a previous github issue that this should be turned off?

        nr_plugin.AgentStartConfiguration agentConfig = new nr_plugin.AgentStartConfiguration(
            crashReportingEnabled: true,
            loggingEnabled: true,
            logLevel: nr_plugin.LogLevel.INFO,
            collectorAddress: "DEFAULT",
            crashCollectorAddress: "DEFAULT",
            analyticsEventEnabled: true,
            networkErrorRequestEnabled:true,
            networkRequestEnabled: true, 
            interactionTracingEnabled: false, //<--- turn this to false. The default setting is true.
            webViewInstrumentation: true,
            fedRampEnabled: false,
            offlineStorageEnabled: true,
            backgroundReportingEnabled: false,
            newEventSystemEnabled: true);

## Steps to Reproduce
Please see above

## Expected Behavior
No crashes

## Relevant Logs / Console output
Please see above

## Your Environment
Release Mode, linker off

## Additional context
iOS 18.0.1, iPhone 11
JetBrains Rider IDE
.Net 8.0.402 .Net MAUI workloads to match, all versions are pinned
New Relic Maui plugin 1.1.3
(I need to file another report because if I updated to 1.1.4, the app crashes on startup in release mode on iOS, but I need to get some logs from the console, because I don't get a crash report. It crashes on startup. )

**Comment by ndesai-newrelic** [comment]
@robin-schroeder-merc I recommend disabling interaction tracing because this issue is primarily related to swizzling, which occurred on the native side.

**Comment by robin-schroeder-merc** [comment]
I wonder if it should be turned off my default? That might help newer folks.

**Comment by ndesai-newrelic** [comment]
@robin-schroeder-merc it is already turn off by Default.
